const ifoodUrl = "https://www.ifood.com.br/delivery/barueri-sp/julius-burger-parque-imperial/396e04a7-10f7-4273-9d0b-1126e4855753";
const whatsappUrl = "https://wa.me/5511986674098?text=Ol%C3%A1%2C%20vim%20pelo%20site%20da%20Juliu%27s%20Burgers%20e%20gostaria%20de%20fazer%20um%20pedido.";

const highlights = [
  { icon: "🔥", title: "Feito na hora", text: "Lanches preparados para chegar quentinhos e cheios de sabor." },
  { icon: "🛵", title: "Delivery prático", text: "Peça com poucos cliques pelo iFood ou fale com a nossa equipe." },
  { icon: "⭐", title: "Sabor do Imperial", text: "Uma hamburgueria do bairro, feita para quem ama um lanche caprichado." },
];

export default function Home() {
  return (
    <main>
      <header className="topbar"><a className="brand" href="#inicio"><img src="/julius-logo-official.jpeg" alt="Logo da Juliu's Burgers" /></a><nav><a href="/cardapio">Cardápio</a><a href="#fidelidade">Pontos</a><a href="#local">Localização</a></nav><a className="miniCta" href={whatsappUrl} target="_blank" rel="noreferrer">Pedir no WhatsApp</a></header>
      <section className="hero" id="inicio"><div className="heroGlow"/><div className="heroCopy"><span className="eyebrow">A FOME BATEU? A JULIU’S RESOLVE.</span><h1>Seu próximo lanche<br/><em>favorito.</em></h1><p>Hambúrguer caprichado, combinação que dá água na boca e entrega prática no Parque Imperial. Escolha como pedir e aproveite cada mordida.</p><div className="actions"><a className="primary" href="/cardapio">Ver o cardápio <span>→</span></a><a className="secondary whatsappBtn" href={whatsappUrl} target="_blank" rel="noreferrer">Pedir pelo WhatsApp</a></div><div className="heroNotes"><span>✓ Cardápio completo no site</span><span>✓ Delivery rápido e quentinho</span><span>✓ Programa de pontos</span></div></div><div className="heroFood"><img src="/food/banner.jpg" alt="Hambúrguer da Juliu's com queijo, bacon, salada e batata frita"/><span>Feito para dar água na boca.</span></div></section>
      <section className="ticker"><span>BURGER ARTESANAL</span><b>✦</b><span>COMBOS</span><b>✦</b><span>BATATA CROCANTE</span><b>✦</b><span>DELIVERY</span></section>
      <section className="section" id="sabores"><div className="sectionHead"><div><span className="eyebrow dark">POR QUE ESCOLHER A JULIU’S?</span><h2>Seu pedido, do seu jeito.</h2></div><p>Uma experiência simples: escolher, pedir e aproveitar.</p></div><div className="cards">{highlights.map((item)=><article key={item.title}><span>{item.icon}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><div className="menuBanner"><div><span className="eyebrow">CARDÁPIO COMPLETO</span><h2>Hoje tem Juliu’s.</h2><p>Confira lanches, porções, bebidas, combos e promoções disponíveis no iFood.</p></div><a className="primary light" href={ifoodUrl} target="_blank" rel="noreferrer">Ver cardápio no iFood →</a></div></section>
      <section className="loyalty" id="fidelidade"><div className="coin">J<span>★</span></div><div><span className="eyebrow">CLUBE DE VANTAGENS</span><h2>Seu pedido vale pontos.</h2><p>A cada <strong>R$ 1,00</strong> em compras você ganha <strong>1 ponto</strong>, que pode ser trocado por recompensas.</p><p className="welcome">Novos clientes ganham automaticamente <strong>5 pontos de boas-vindas.</strong></p></div><a className="secondary warm" href="https://juliusburgers.com.br/" target="_blank" rel="noreferrer">Conhecer o programa</a></section>
      <section className="location" id="local"><div className="locationCopy"><span className="eyebrow dark">ENCONTRE A GENTE</span><h2>No coração do Parque Imperial.</h2><address>Rua Di Cavalcanti, 283<br/>Parque Imperial — Barueri/SP<br/>CEP 06462-210</address><div className="actions"><a className="primary" href="https://www.google.com/maps/search/?api=1&query=Rua+Di+Cavalcanti+283+Parque+Imperial+Barueri" target="_blank" rel="noreferrer">Abrir no mapa →</a><a className="secondary darkBtn" href={whatsappUrl} target="_blank" rel="noreferrer">Falar conosco</a></div></div><div className="hours"><h3>Horários informados</h3><div><span>Segunda-feira</span><strong>Fechado</strong></div><div><span>Terça a quinta</span><strong>18h — 00h</strong></div><div><span>Sexta a domingo</span><strong>19h — 01h</strong></div><small>Consulte o iFood para confirmar o atendimento do dia.</small></div></section>
      <a className="floatingWhatsapp" href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Fazer pedido pelo WhatsApp">WhatsApp <span>→</span></a>
      <footer><div className="footerBrand"><img src="/julius-logo-official.jpeg" alt="Juliu's Burgers"/><p>O sabor que mora no Parque Imperial.</p></div><div><h4>Pedidos e contato</h4><a href="/cardapio">Ver cardápio</a><a href={ifoodUrl} target="_blank" rel="noreferrer">Pedir pelo iFood</a><a href={whatsappUrl} target="_blank" rel="noreferrer">(11) 98667-4098</a><a href="https://www.instagram.com/julius.burgers/" target="_blank" rel="noreferrer">@julius.burgers</a></div><div><h4>Dados da empresa</h4><p>Juliosburguer</p><p>Responsável: Brenda Dias Moura</p><p>CNPJ 52.795.519/0001-07</p><p>Rua Di Cavalcanti, 283 — Parque Imperial, Barueri/SP</p></div><div className="copyright">© 2026 Juliu’s Burgers. Todos os direitos reservados.</div></footer>
    </main>
  );
}
