const whatsapp = (item="") => "https://wa.me/5511986674098?text=" + encodeURIComponent("Olá, vim pelo site da Juliu's Burgers e quero pedir " + item);
const products = {
  promocao:[{name:"Burger do Palhaço em Dobro",desc:"2 lanches, cada um com 2 hambúrgueres, alface, queijo, molho especial, cebola e picles no pão com gergelim.",price:"R$ 40,00",old:"R$ 50,00",tag:"-20%",image:"/food/palhaco-em-dobro.png"}],
  porcoes:[{name:"Batata Frita Simples",desc:"Crocante por fora e macia por dentro.",price:"R$ 13,00"},{name:"Nuggets + maionese da casa",desc:"6 unidades de nuggets de frango.",price:"R$ 12,50",sold:true},{name:"Anel de cebola + barbecue",desc:"6 anéis de cebola empanados com molho barbecue.",price:"R$ 12,50"}],
  tradicionais:[{name:"X-Burguer",desc:"Pão, hambúrguer de 60g, queijo tipo cheddar e maionese.",price:"R$ 12,00"},{name:"X-Salada",desc:"Hambúrguer, queijo tipo cheddar, alface, tomate e maionese.",price:"R$ 14,00"},{name:"X-Calabresa",desc:"Pão da casa, hambúrguer, queijo, calabresa, alface, tomate e maionese.",price:"R$ 16,00"},{name:"X-Egg",desc:"Hambúrguer de 60g, ovo, queijo, alface, tomate e maionese.",price:"R$ 16,00"}],
  queridinhos:[{name:"Burger do Palhaço",desc:"2 hambúrgueres, alface, queijo, molho especial, cebola e picles no pão com gergelim.",price:"R$ 25,00",image:"/food/instagram-1.jpg"}],
  molhos:[{name:"Molho Tasty",desc:"30ml do molho com gostinho de churrasco.",price:"R$ 3,00"},{name:"Molho Barbecue",desc:"Porção individual.",price:"R$ 3,00"},{name:"Molho Especial",desc:"Porção individual.",price:"R$ 3,00"}],
  bebidas:[{name:"Coca-Cola 350ml",price:"R$ 7,00"},{name:"Coca-Cola Zero 350ml",price:"R$ 7,00"},{name:"Fanta Uva 350ml",price:"R$ 7,00"},{name:"Fanta Laranja",price:"R$ 7,00",sold:true},{name:"Fanta Guaraná",price:"R$ 7,00"},{name:"Del Valle Uva 290ml",price:"R$ 7,00"},{name:"Del Valle Goiaba 290ml",price:"R$ 7,00"},{name:"Coca-Cola 1L",price:"R$ 13,00"},{name:"Coca-Cola 2L",price:"R$ 18,00"},{name:"Draft Chopp de Vinho",price:"R$ 15,00",sold:true},{name:"Skol 269ml",price:"R$ 4,50"},{name:"Dolly Guaraná",price:"R$ 10,00"}],
  sobremesas:[{name:"Paçoca",price:"R$ 2,00"}],
};
type Product = {name:string;desc?:string;price:string;old?:string;tag?:string;sold?:boolean;image?:string};
function Card({p}:{p:Product}){return <article className={"productCard "+(p.sold?"sold":"")}>
  {p.image&&<img src={p.image} alt={p.name}/>}<div className="productInfo">{p.tag&&<span className="discount">{p.tag}</span>}<h3>{p.name}</h3>{p.desc&&<p>{p.desc}</p>}<div className="productBottom"><div>{p.old&&<del>{p.old}</del>}<strong>{p.price}</strong></div>{p.sold?<span className="soldLabel">Esgotado</span>:<a href={whatsapp(p.name)} target="_blank" rel="noreferrer">Pedir →</a>}</div></div>
  </article>}
function Section({id,title,items}:{id:string;title:string;items:Product[]}){return <section className="menuGroup" id={id}><div className="groupTitle"><span>JULIU’S</span><h2>{title}</h2></div><div className="productGrid">{items.map(p=><Card key={p.name} p={p}/>)}</div></section>}
export default function Cardapio(){return <main className="menuPage">
  <header className="topbar"><a className="brand" href="/"><img src="/julius-logo-official.jpeg" alt="Juliu's Burgers"/></a><nav><a href="/">Início</a><a href="#promocoes">Promoções</a><a href="/#local">Localização</a></nav><a className="miniCta" href={whatsapp()} target="_blank" rel="noreferrer">Pedir no WhatsApp</a></header>
  <section className="catalogHero"><div><span className="eyebrow">CARDÁPIO COMPLETO</span><h1>Escolha o seu<br/><em>Juliu’s.</em></h1><p>Veja os lanches, porções, molhos e bebidas sem sair do site. Encontrou o seu? É só pedir direto no WhatsApp.</p></div><img src="/food/instagram-2.jpg" alt="Hambúrguer da Juliu's com batata frita e refrigerante"/></section>
  <nav className="categoryNav" aria-label="Categorias do cardápio"><a href="#promocoes">🔥 Promoções</a><a href="#porcoes">🍟 Porções</a><a href="#tradicionais">🍔 Tradicionais</a><a href="#queridinhos">⭐ Queridinhos</a><a href="#molhos">🥫 Molhos</a><a href="#bebidas">🥤 Bebidas</a><a href="#sobremesas">🍬 Sobremesas</a></nav>
  <div className="catalog"><Section id="promocoes" title="Promoções" items={products.promocao}/><Section id="porcoes" title="Porções" items={products.porcoes}/><Section id="tradicionais" title="Tradicionais da Juliu’s" items={products.tradicionais}/><Section id="queridinhos" title="Queridinhos da galera" items={products.queridinhos}/><Section id="molhos" title="Molhos que não podem faltar" items={products.molhos}/><Section id="bebidas" title="Bebidas" items={products.bebidas}/><Section id="sobremesas" title="Sobremesas" items={products.sobremesas}/></div>
  <section className="menuGallery"><img src="/food/banner.jpg" alt="Hambúrguer artesanal da Juliu's"/><img src="/food/instagram-1.jpg" alt="Lanches da Juliu's"/><img src="/food/instagram-2.jpg" alt="Combo da Juliu's"/></section>
  <aside className="priceNote">Cardápio e preços consultados no canal oficial da Juliu’s. Itens podem ficar indisponíveis durante o atendimento.</aside>
  <a className="floatingWhatsapp" href={whatsapp()} target="_blank" rel="noreferrer">WhatsApp <span>→</span></a>
  <footer><div className="footerBrand"><img src="/julius-logo-official.jpeg" alt="Juliu's Burgers"/><p>O sabor que mora no Parque Imperial.</p></div><div><h4>Navegação</h4><a href="/">Página inicial</a><a href="#promocoes">Promoções</a><a href={whatsapp()} target="_blank" rel="noreferrer">WhatsApp</a></div><div><h4>Dados da empresa</h4><p>Juliosburguer</p><p>Responsável: Brenda Dias Moura</p><p>CNPJ 52.795.519/0001-07</p><p>Rua Di Cavalcanti, 283 — Parque Imperial, Barueri/SP</p></div><div className="copyright">© 2026 Juliu’s Burgers. Todos os direitos reservados.</div></footer>
</main>}
